### PR TITLE
fix: Now lasertext is not displayed in ddr other team

### LINKED ISSUE #355: fng: lasertext is displayed in other teams
If you go into the team, the laser text is globally visible, which it shouldn't be. 

I would fix it myself and submit a fix request, but I'm still not familiar enough with the issue, even though I threw it in.

### PR DESCRIPTION
**Pull request by ByFox213**
Closed: #355

### CODE REVIEW

File: src/game/server/gamemodes/instagib/base_fng.cpp [hunk 1]
```diff
@@ -335,7 +335,7 @@ inline void CGameControllerBaseFng::UpdateScoresAndDisplayPoints(CPlayer *pKille
 	pKiller->AddScore(PlayerScore - 1);
 	AddTeamscore(pKiller->GetTeam(), TeamScore);
 	if(pKiller->IsPlaying()) // NOLINT(clang-analyzer-unix.Malloc)
-		MakeLaserTextPoints(pKiller->GetCharacter()->GetPos(), PlayerScore, 3); // NOLINT(clang-analyzer-unix.Malloc)
+		MakeLaserTextPoints(pKiller->GetCharacter()->GetPos(), PlayerScore, 3, pKiller->GetCharacter()->TeamMask()); // NOLINT(clang-analyzer-unix.Malloc)
```
Comment (ChillerDragon) [inline src/game/server/gamemodes/instagib/base_fng.cpp:338]: This looks unsafe. Are you sure `pKiller->GetCharacter()` is never `nullptr`? Cant you trigger a score while being dead or spectator?

Comment (ChillerDragon) [reply src/game/server/gamemodes/instagib/base_fng.cpp:338]: Ah yes looks safe lol it is already used in the same line lol, never mind xd

Comment (ChillerDragon) [reply src/game/server/gamemodes/instagib/base_fng.cpp:338]: Oh IsPlaying guards it. I did not know that method.

```C++
bool CPlayer::IsPlaying() const
{
	return m_pCharacter && m_pCharacter->IsAlive();
}
```

File: src/game/server/instagib/laser_text.cpp [hunk 2]
```diff
@@ -491,7 +494,10 @@ void CLaserText::MakeLaser(char Char, int CharOffset, int &CharCount)
 
 void CLaserText::Snap(int SnappingClient)
 {
-	if(NetworkClipped(SnappingClient))
+	if(NetworkClipped(SnappingClient) && NetworkClipped(SnappingClient, m_Pos))
```
Comment (ChillerDragon) [inline src/game/server/instagib/laser_text.cpp]: What was the motivation for that change? Looks like a duplicate to me. The `NetworkClipped(int)` is a wrapper that calls it with `m_Pos`

https://github.com/ddnet-insta/ddnet-insta/blob/6341a92c3633df36bb52a1e0400f8674c312c77a/src/game/server/entity.cpp#L36-L42

**Comment by ChillerDragon** [comment]
Tested it in game. Works well thanks for working on this :heart:

File: src/game/server/gamemodes/instagib/base_fng.cpp (hunk 1 above)
Comment (ByFox213) [reply src/game/server/gamemodes/instagib/base_fng.cpp:338]: xD

File: src/game/server/instagib/laser_text.cpp (hunk 2 above)
Comment (ByFox213) [reply src/game/server/instagib/laser_text.cpp]: https://github.com/ddnet-insta/ddnet-insta/blob/insta/src%2Fgame%2Fserver%2Fentities%2Flaser.cpp#L297

I was basing it on CLaser at the moment, but after what you said, the second one is really useless

**Comment by ByFox213** [comment]
I forgot to move asciiTable to laser_text.h

**Comment by ChillerDragon** [comment]
> I forgot to move asciiTable to laser_text.h

Why move?

**Comment by ByFox213** [comment]
> Why move?

I usually try to store static in .h

**Comment by ChillerDragon** [comment]
Thanks
